default:
  n_sample_size:
    - 250
    - 500
    - 1000
    - 2000
    - 4000
  protected_inflation: 0
  doomed_inflation: 0
  effect_protect: TRUE
  protected_epsilon: 1
  doomed_epsilon: 1
  immune_delta: 0
  protected_delta: 0
  S_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  S_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_Z_X: "Y ~ Z * X1 * X2 * X3"
  Y_X_S1: "Y ~ X1 * X2 * X3"
  Y_X_S0: "Y ~ X1 * X2 * X3"
  S_X: "S ~ X1 * X2 * X3"
  S_Z_X: NULL
  Z_X: "Z ~ X1 * X2 * X3"
  
# ------------------------------------------------------------------------

provide_immune_30_ve_66:
  n_sample_size:
    - 700
  protected_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  doomed_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  effect_protect: TRUE
  protected_epsilon: 1
  doomed_epsilon: 1
  immune_delta: -1.18
  protected_delta: -0.13
  S_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  S_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
    
provide_immune_40_ve_66:
  n_sample_size:
    - 700
  protected_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  doomed_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  effect_protect: TRUE
  protected_epsilon: 1
  doomed_epsilon: 1
  immune_delta: -0.73
  protected_delta: -0.12
  S_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  S_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
    
provide_immune_50_ve_66:
  n_sample_size:
    - 700
  protected_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  doomed_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  effect_protect: TRUE
  protected_epsilon: 1
  doomed_epsilon: 1
  immune_delta: -0.32
  protected_delta: -0.11
  S_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  S_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
    
provide_immune_60_ve_66:
  n_sample_size:
    - 700
  protected_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  doomed_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  effect_protect: TRUE
  protected_epsilon: 1
  doomed_epsilon: 1
  immune_delta: 0.16
  protected_delta: -0.19
  S_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  S_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
    
provide_immune_70_ve_66:
  n_sample_size:
    - 700
  protected_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  doomed_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  effect_protect: TRUE
  protected_epsilon: 1
  doomed_epsilon: 1
  immune_delta: 0.6
  protected_delta: -0.17
  S_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  S_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
    
provide_immune_80_ve_66:
  n_sample_size:
    - 700
  protected_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  doomed_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  effect_protect: TRUE
  protected_epsilon: 1
  doomed_epsilon: 1
  immune_delta: 1.11
  protected_delta: -0.11
  S_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  S_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
    
provide_immune_70_ve_50:
  n_sample_size:
    - 700
  protected_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  doomed_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  effect_protect: TRUE
  protected_epsilon: 1
  doomed_epsilon: 1
  immune_delta: 0.18
  protected_delta: 0.53
  S_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  S_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
    
provide_immune_70_ve_85:
  n_sample_size:
    - 700
  protected_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  doomed_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  effect_protect: TRUE
  protected_epsilon: 1
  doomed_epsilon: 1
  immune_delta: 1.3
  protected_delta: -1.09
  S_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  S_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
 
provide_immune_60_ve_50:
  n_sample_size:
    - 700
  protected_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  doomed_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  effect_protect: TRUE
  protected_epsilon: 1
  doomed_epsilon: 1
  immune_delta: -0.29
  protected_delta: 0.55
  S_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  S_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
    
provide_immune_60_ve_85:
  n_sample_size:
    - 700
  protected_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  doomed_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  effect_protect: TRUE
  protected_epsilon: 1
  doomed_epsilon: 1
  immune_delta: 0.95
  protected_delta: -1.21
  S_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  S_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
    
provide_immune_40_ve_50:
  n_sample_size:
    - 700
  protected_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  doomed_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  effect_protect: TRUE
  protected_epsilon: 1
  doomed_epsilon: 1
  immune_delta: -1.16
  protected_delta: 0.59
  S_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  S_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
    
provide_immune_40_ve_85:
  n_sample_size:
    - 700
  protected_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  doomed_inflation: [0, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -1, -1.1, -1.2, -1.3, -1.4, -1.5, -1.6, -1.7, -1.8, -1.9, -2, -2.1, -2.2, -2.3, -2.4, -2.5, -2.6, -2.7, -2.8, -2.9, -3]
  effect_protect: TRUE
  protected_epsilon: 1
  doomed_epsilon: 1
  immune_delta: 0.1
  protected_delta: -1.19
  S_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  S_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
  Y_Z_X_library:
    - "SL.glm"
    - "SL.earth.mod"
    - "SL.gam"
    - "SL.step.forward"
    