default:
  n_sample_size:
    - 250
    - 500
    - 1000
    - 2000
    - 4000
  nat_inf_inflation: 0
  doomed_inflation: 0
  effect_protect: TRUE
  nat_inf_epsilon: 1
  doomed_epsilon: 1
  Y_Z_X: "Y ~ Z * X1 * X2 * X3"
  Y_X_S1: "Y ~ X1 * X2 * X3"
  Y_X_S0: "Y ~ X1 * X2 * X3"
  S_X: "S ~ X1 * X2 * X3"
  S_Z_X: NULL
  Z_X: "Z ~ X1 * X2 * X3"
  
contour_plot:
  n_sample_size:
    - 2000
  nat_inf_inflation: [0, 0.25, 0.5, 0.75, 1]
  doomed_inflation: [0, 0.25, 0.5, 0.75, 1]
  effect_protect: TRUE
  nat_inf_epsilon: 1
  doomed_epsilon: 1
  Y_Z_X: "Y ~ Z * X1 * X2 * X3"
  Y_X_S1: "Y ~ X1 * X2 * X3"
  Y_X_S0: "Y ~ X1 * X2 * X3"
  S_X: "S ~ X1 * X2 * X3"
  S_Z_X: NULL
  Z_X: "Z ~ X1 * X2 * X3"
